export enum PermissionEnum {
  // Nhóm khách hàng
  CUSTOMER_GROUP_CREATE = 'CUSTOMER_GROUP_CREATE',
  CUSTOMER_GROUP_UPDATE = 'CUSTOMER_GROUP_UPDATE',
  CUSTOMER_GROUP_DELETE = 'CUSTOMER_GROUP_DELETE',
  CUSTOMER_GROUP_VIEW = 'CUSTOMER_GROUP_VIEW',

  // Khách hàng
  CUSTOMER_CREATE = 'CUSTOMER_CREATE',
  CUSTOMER_UPDATE = 'CUSTOMER_UPDATE',
  CUSTOMER_DELETE = 'CUSTOMER_DELETE',
  CUSTOMER_VIEW = 'CUSTOMER_VIEW',

  // Nhóm nhà cung cấp
  SUPPLIER_GROUP_CREATE = 'SUPPLIER_GROUP_CREATE',
  SUPPLIER_GROUP_UPDATE = 'SUPPLIER_GROUP_UPDATE',
  SUPPLIER_GROUP_DELETE = 'SUPPLIER_GROUP_DELETE',
  SUPPLIER_GROUP_VIEW = 'SUPPLIER_GROUP_VIEW',

  // Nhà cung cấp
  SUPPLIER_CREATE = 'SUPPLIER_CREATE',
  SUPPLIER_UPDATE = 'SUPPLIER_UPDATE',
  SUPPLIER_DELETE = 'SUPPLIER_DELETE',
  SUPPLIER_VIEW = 'SUPPLIER_VIEW',

  // Nhóm sản phẩm
  PRODUCT_GROUP_CREATE = 'PRODUCT_GROUP_CREATE',
  PRODUCT_GROUP_UPDATE = 'PRODUCT_GROUP_UPDATE',
  PRODUCT_GROUP_DELETE = 'PRODUCT_GROUP_DELETE',
  PRODUCT_GROUP_VIEW = 'PRODUCT_GROUP_VIEW',

  // Nhà sản xuất
  MANUFACTURER_CREATE = 'MANUFACTURER_CREATE',
  MANUFACTURER_UPDATE = 'MANUFACTURER_UPDATE',
  MANUFACTURER_DELETE = 'MANUFACTURER_DELETE',
  MANUFACTURER_VIEW = 'MANUFACTURER_VIEW',

  // Vị trí sản phẩm
  PRODUCT_LOCATION_CREATE = 'PRODUCT_LOCATION_CREATE',
  PRODUCT_LOCATION_UPDATE = 'PRODUCT_LOCATION_UPDATE',
  PRODUCT_LOCATION_DELETE = 'PRODUCT_LOCATION_DELETE',
  PRODUCT_LOCATION_VIEW = 'PRODUCT_LOCATION_VIEW',

  // Đường dùng thuốc
  MEDICINE_ROUTE_CREATE = 'MEDICINE_ROUTE_CREATE',
  MEDICINE_ROUTE_UPDATE = 'MEDICINE_ROUTE_UPDATE',
  MEDICINE_ROUTE_DELETE = 'MEDICINE_ROUTE_DELETE',
  MEDICINE_ROUTE_VIEW = 'MEDICINE_ROUTE_VIEW',

  // Sản phẩm
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',
  PRODUCT_VIEW = 'PRODUCT_VIEW',

  // Phương thức thanh toán
  PAYMENT_METHOD_UPSERT = 'PAYMENT_METHOD_UPSERT',

  // Hóa đơn
  INVOICE_CREATE = 'INVOICE_CREATE',
  INVOICE_CANCEL = 'INVOICE_CANCEL',
  INVOICE_VIEW = 'INVOICE_VIEW',

  // Lô sản phẩm
  PRODUCT_LOT_CREATE = 'PRODUCT_LOT_CREATE',
  PRODUCT_LOT_UPDATE = 'PRODUCT_LOT_UPDATE',
  PRODUCT_LOT_DELETE = 'PRODUCT_LOT_DELETE',
  PRODUCT_LOT_VIEW = 'PRODUCT_LOT_VIEW',

  // Giao dịch kho
  STOCK_TRANSACTION_CREATE = 'STOCK_TRANSACTION_CREATE',
  STOCK_TRANSACTION_UPDATE = 'STOCK_TRANSACTION_UPDATE',
  STOCK_TRANSACTION_CANCEL = 'STOCK_TRANSACTION_CANCEL',
  STOCK_TRANSACTION_VIEW = 'STOCK_TRANSACTION_VIEW',

  // Người dùng
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_VIEW = 'USER_VIEW',

  // Nhóm quyền
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_VIEW = 'ROLE_VIEW',

  // Thẻ kho
  STOCK_CARD_VIEW = 'STOCK_CARD_VIEW',

  // Báo cáo
  REPORT_VIEW = 'REPORT_VIEW'
}
