export enum StockCardTypeEnum {
  INVOICE = 'INVOICE',
  STOCK_TRANSACTION_IMPORT = 'STOCK_TRANSACTION_IMPORT',
  STOCK_TRANSACTION_CANCEL = 'STOCK_TRANSACTION_CANCEL',
  STOCK_TRANSACTION_CHECK = 'STOCK_TRANSACTION_CHECK'
}
